### ISSUE TITLE
sampling without replacement

### ISSUE THREAD

**Issue by ahsimb** [deepmind/reverb#10]
There doesn't seem to be a way of doing sampling without replacement. 
Is this true?
Are there any plans to provide this option in future releases?

**Comment by fastturtle** [comment]
Hi @ahsimb you're right that there is no way of doing sampling without replacement. At the moment we have no plans to provide this option in a future release.

**Comment by fastturtle** [comment]
Closing this issue, but feel free to re-open if you have further comments or questions.
