### ISSUE TITLE
Is there a way to modify data inplace in the table?

### ISSUE THREAD

**Issue by EdanToledo** [deepmind/reverb#101]
Hello, basically my title says it all. I would like to have separate worker that is able to modify data values in the table. For example - the worker would sample the data, perform some processing and change the values of some fields. An example of something like this is Muzero Reanalyse. Does reverb support any functionality like this? Thanks so much.

**Comment by EdanToledo** [comment]
Leaving a comment here to say I'm still looking for any sort of functionality like this. Thanks

**Comment by qstanczyk** [comment]
Hi, you can just insert the same item again (with the same ID), it will get updated.

**Comment by qstanczyk** [comment]
Please reopen if this is still an issue.
