### ISSUE TITLE
Enable delta compression for the new trajectory writer.

### ISSUE THREAD

**Issue by ethanluoyc** [deepmind/reverb#102]
Hi,

I would like to test if it's possible to leverage Reverb's delta compression to reduce the memory footprint of a pixel-based agent developed on top of Acme with Reverb. I find even without enabling this, Reverb provides quite good savings on the memory compared to the raw, uncompressed tensors, still, I imagine turning this on should provide additional memory saving. Is that correct?

It seems that there is an option in the C++ implementation of the trajectory writer that can enable delta compression, but that API is not exposed from the pybind bindings. Is it possible to expose that API via the Python interface?

**Comment by qstanczyk** [comment]
We plan to automatically decide whether to enable delta compression or not, so there is no need for the user to worry about it. For that reason we don't plan to expose the flag in the API.
