### ISSUE TITLE
hanging after  `Started replay server on port `

### ISSUE THREAD

**Issue by gitlabspy** [deepmind/reverb#107]
```
[reverb/cc/platform/tfrecord_checkpointer.cc:162]  Initializing TFRecordCheckpointer in /tmp/tmpdtpkiw2f.
[reverb/cc/platform/tfrecord_checkpointer.cc:552] Loading latest checkpoint from /tmp/tmpdtpkiw2f
[reverb/cc/platform/default/server.cc:71] Started replay server on port 42239
```
I was running codes from tf-agents' examples and hangs when setting up reverb.
https://www.tensorflow.org/agents/tutorials/7_SAC_minitaur_tutorial#replay_buffer

**Comment by acassirer** [comment]
Hey, 

Please ask this question in tf_agent instead as there is no issue with Reverb.
