### ISSUE TITLE
table signature (shapes) must be same for each field of structured data?

### ISSUE THREAD

**Issue by unacao** [deepmind/reverb#117]
Hi, I am new to reverb, and I am trying to insert a dict data as a sample in the replay buffer. It may look like
{'ground_truth_labels':[x, x, x], 'ground_truth_positions':[x, x, x]} The number of elements in the array of each field 'ground_truth_labels' & 'ground_truth_positions' can vary from one training sample to another. I am able to insert all the training data. However when trying to sample it, it seems to require either table signature or (dtypes, shapes) as input to a dataset. If I sample from client directly, it seems to lose all the field names. Does that mean reverb is not suitable for my training data since shape needs to be fixed for each field?

**Comment by acassirer** [comment]
Hey,

Reverb doesn't really make any strong assumptions that the data maintains the same spec across samples but Tensorflow datasets does. If you literally means that `ground_truth_labels` holds a list of tensors of some spec then I can't really think of a good solution for you as the number of tensors would vary between samples. If however you instead mean that `ground_truth_labels` is a single tensor but with a varying leading dimension then you might be able to construct a dataset using a shape with `None` as the leading dimension for these tensors. I'm not sure that will work though but could be worth a try.

**Comment by unacao** [comment]
ground_truth_labels is a single tensor, and your suggestion works great! Thank you!
