### ISSUE TITLE
Sampling from a loaded replay checkpoint

### ISSUE THREAD

**Issue by bmazoure** [deepmind/reverb#118]
I'm testing a pipeline where I train a SAC agent, checkpoint its replay buffer and then try to restore it. The `client.server_info()` command seems to indicate that the checkpoint is loaded fine:
```
{'priority_table': TableInfo(name='priority_table', sampler_options=uniform: true
, remover_options=fifo: true
is_deterministic: true
, max_size=1000000, max_times_sampled=0, rate_limiter_info=samples_per_insert: 256.0
min_diff: 115200.0
max_diff: 1.7976931348623157e+308
min_size_to_sample: 500
insert_stats {
  completed: 100073
}
sample_stats {
  completed: 25503488
}
, signature=Transition(observation=TensorSpec(shape=(2,), dtype=tf.float32, name='observation'), action=TensorSpec(shape=(1,), dtype=tf.float32, name='action'), reward=TensorSpec(shape=(), dtype=tf.float32, name='reward'), discount=TensorSpec(shape=(), dtype=tf.float32, name='discount'), next_observation=TensorSpec(shape=(2,), dtype=tf.float32, name='next_observation'), extras=()), current_size=100073, num_episodes=1169, num_deleted_episodes=0, num_unique_samples=99701, table_worker_time=sleeping_ms: 11776
)}
```

However, running the following causes a `StopIteration` exception:

```
dataset = reverb.TimestepDataset.from_table_signature(
        server_address=f'localhost:{server.port}',
        table='priority_table',
        max_in_flight_samples_per_worker=1,
        rate_limiter_timeout_ms=10).batch(1).as_numpy_iterator().__next__()
```

I suspect that the server somehow gets closed before sampling. Any ideas on what might be happening?

**Comment by acassirer** [comment]
Hi Bogdan,

Just eyeballing the numbers in that `server_info` indicates to me that you can't sample from that table as it hitting the `samples_per_insert` ratio. I.e. the number of completed samples (`25503488`) is roughly `256` times bigger than the number of completed inserts (`100073`).

We can verify that this is correct by doing the [math that the rate limiter does to check if samples are allowed](https://github.com/deepmind/reverb/blob/master/reverb/cc/rate_limiter.cc#L113-L114):

> 100073 * 256 - 25503488 = 115200

We can then compare that to the `min_diff` in the `server_info` response and see that they are exactly the same. This means that sampling one more item would violate rate limiter and thus the sample action is blocked.

If you were to sample without specifying a `rate_limiter_timeout_ms` in the dataset constructor then it would block forever but you do specify it so the dataset will "complete" after 10ms and raise the `StopIteration` exception.

I'm afraid that the checkpointing in Reverb was designed exclusively for handling unexpected experiment failures and the data format therefore is not very useful if you wish to reuse the data from a previous experiment in a new one. If you want to hack around this then I would suggest doing some hackery to manually change the value of `min_diff` in the raw checkpoint file.

**Comment by bmazoure** [comment]
@acassirer Thanks for the thorough explanation, I definitely understand how checkpointing works a bit better now! I've manually changed the `RateLimiter` loaded from the checkpoint to have these `client.server_info()` stats:

```
{'priority_table': TableInfo(name='priority_table', sampler_options=uniform: true
 , remover_options=fifo: true
 is_deterministic: true
 , max_size=1000000, max_times_sampled=0, rate_limiter_info=samples_per_insert: 256.0
 min_diff: 2.2250738585072014e-308
 max_diff: 1.7976931348623157e+308
 min_size_to_sample: 500
 insert_stats {
   completed: 50048
 }
 sample_stats {
   completed: 12812287
 }
 , signature=Transition(observation=TensorSpec(shape=(2,), dtype=tf.float32, name='observation'), action=TensorSpec(shape=(1,), dtype=tf.float32, name='action'), reward=TensorSpec(shape=(), dtype=tf.float32, name='reward'), discount=TensorSpec(shape=(), dtype=tf.float32, name='discount'), next_observation=TensorSpec(shape=(2,), dtype=tf.float32, name='next_observation'), extras=()), current_size=50048, num_episodes=577, num_deleted_episodes=0, num_unique_samples=49839, table_worker_time=running_ms: 34171
 sampling_ms: 1421
 inserting_ms: 486
 sleeping_ms: 262707
 waiting_for_inserts_ms: 3657805
 )}
```
However, I'm still getting a `StopIteration` exception. The `min_diff` is set to `-inf` so I'm not sure what's blocking it now?

Thanks a lot!

**Comment by acassirer** [comment]
`min_diff: 2.2250738585072014e-308`

This doesn't look like a negative number to me but more like (almost) `0`. Doing the math again for the rate limiter we get:

> 50048 *256 - 12812287 = 1

So if we were to sample once more then that becomes `0` which is smaller than `2.2250738585072014e-308` so it looks like you are hitting the same thing as before but with new numbers. I'm guessing that the `-inf` might have resulted in some overflow issue.

Maybe you'll have better luck if you tweaked the `sample_stats.completed` and/or `samples_per_insert`?

_Just to be clear: if you never insert any more data then it will always eventually reach the `StopIteration`._

**Comment by bmazoure** [comment]
Oh, you're right, I was not paying attention and didn't see that `sys.float_info.min` is close to `0` and not `-inf`. Setting `min_dif=-sys.float_info.max` did the job and everything is working. Thanks a lot!
