### ISSUE TITLE
How to use the checkpointer to save replay buffer in the disk?

### ISSUE THREAD

**Issue by fmxFranky** [deepmind/reverb#12]
I found that there are no files in the directory of the checkpointer's folder, neigther /tmp/xxxxx or the specific predefined directory.
I also noticed that the `TFCheckpointer` class have inferfaces for saving and loading replay buffer, but when i call `replay_checkpointer.save()` i got the error said "Don't have the attribute 'save' ".
So how to use the checkpointer class or reverb's saver class to save replay buffer in the disk?
Thanks~

**Comment by ebrevdo** [comment]
(James gave the solution)
