### ISSUE TITLE
[Conceptual Question] Item creation and sampling trajectories with specified period

### ISSUE THREAD

**Issue by EdanToledo** [deepmind/reverb#132]
Hello, I have a quick conceptual question. I am wondering how sampling occurs in a trajectory dataset when using a specific period. Essentially my question is: do sequences that can be sampled have static indices as items in the buffer? 

For example, lets say I add a sequence of 20 data points and my sample sequence length is 10 with a period of 5, are 3 items created with following indices [0,9], [5, 14], [10, 19] or can a sequence be sampled uniformly with any starting index up to 10 and then subsequent data samples in a batch respect the period of the first sample?

**Comment by acassirer** [comment]
Hi,

The range which the items covers are defined at insert time not at sample time. I.e. if you insert with a sequence length of 10 and period are 5 then you will always end up with sequences which covers exactly the spans you outlined.

Hope that helps clear things up!
