### ISSUE TITLE
Restoring a checkpoint does not restore a checkpoint

### ISSUE THREAD

**Issue by jmacglashan** [deepmind/reverb#14]
Following the readme guidelines, when you trigger a checkpoint, you can provide the path to a `DefaultCheckpointer` and give that to the server to have it restore the state.

This does not actually seems to work. I'm using Reverb version `0.1.0.dev20200716` because later versions crash for me (as I detailed in issue #13 )

Here's a script I wrote to try and get it to work.
```python
import reverb
import tensorflow as tf

OBSERVATION_TABLE = 'OBSERVATION'
PORT = 5000

def start_server(checkpoint_path = None):

    if checkpoint_path:
        checkpointer = reverb.checkpointers.DefaultCheckpointer(checkpoint_path)
    else:
        checkpointer = None

    server = reverb.Server(  # noqa
        tables=[
            reverb.Table(
                name=OBSERVATION_TABLE,
                sampler=reverb.selectors.Uniform(),
                remover=reverb.selectors.Fifo(),
                max_size=1000,
                rate_limiter=reverb.rate_limiters.MinSize(1),
            )
        ],
        port=5000,
        checkpointer=checkpointer
    )

    return server, reverb.client.Client(f'localhost:{PORT}'), reverb.TFClient(f'localhost:{PORT}')


def do_writes(client):
    print('writing data')
    writer = client.writer(1)
    for i in range(10):
        writer.append(tf.constant([i], dtype=tf.float32))
        writer.create_item(OBSERVATION_TABLE, 1, 0.8)


def do_reads():
    print('reading data')
    dataset = reverb.ReplayDataset(f'localhost:{PORT}', OBSERVATION_TABLE, (tf.float32,), (1,), 4)
    for item in dataset.take(20):
        print(item.data)


def insert_run():
    server, client, tf_client = start_server()
    do_writes(client)
    do_reads()

    checkpoint_path = client.checkpoint()
    print(checkpoint_path)
    print('done')


def checkpoint_run(path):
    server, client, tf_client = start_server(path)
    do_reads()
    print('done')


def main():
    # first run this script with this line
    insert_run() 

    # then once you get a checkpoint path from running the above, comment out the above line and uncomment the below
    # below line, but passing it the file path you observed in the previous run. I have an example path here
    # checkpoint_run('/tmp/tmpqv10edqk/2020-08-11T15:16:41.996914817+00:00')


if __name__ == '__main__':
    main()
```

When you run the script using `insert_run()` everything works and you get print outs of data from the dataset as well as a checkpoint path.

When you run the script instead using `checkpoint_run` and providing it the final path reported from the previous run of the script, it blocks indefinitely on the first iteration of the dataset, presumably because it's waiting for the first data to be inserted since it seems to not have actually loaded the table checkpoint.

I can confirm that the file path reported exists with the following contents
```
DONE  chunks.tfrecord  tables.tfrecord
```

I can also confirm that reverb reports using the checkpoint in its output because you can see the following log.
```
[reverb/cc/platform/tfrecord_checkpointer.cc:143] Initializing TFRecordCheckpointer in /tmp/tmpqv10edqk/2020-08-11T15:16:41.996914817+00:00
[reverb/cc/platform/tfrecord_checkpointer.cc:320] Loading latest checkpoint from /tmp/tmpqv10edqk/2020-08-11T15:16:41.996914817+00:00
```

Any thoughts?

*UPDATE* After trying one more idea, I found if I pass the parent directory of the checkpoint path, it will load the data, which presumably is the latest only. 

That solves some of my problems, but it means two things
1. I think the readme is wrong (the returned path from the checkpoint won't work)
2. It means I cannot specify a specific checkpoint, only the latest.

So I think the revised issue is you can't seem to load a specific checkpoint, only the latest.

**Comment by ebrevdo** [comment]
@fastturtle we should be able to point to a specific (not just latest) checkpoint, right?  why does one need to pass the parent directory of the path returned by .checkpoint?

**Comment by acassirer** [comment]
@ebrevdo: The original design only allowed you to load the latest checkpoint since the scope was limited to handling machine preemption and nothing else. There haven't been any major changes to the original design since with the exception of [`fallback_checkpoint_path`](https://github.com/deepmind/reverb/blob/a5cde5992fd806de1aeec96a3f749a6787b03563/reverb/platform/checkpointers_lib.py#L40) which allows you to override the default behaviour and load a specific checkpoint when the server is brought up.

**Comment by ebrevdo** [comment]
@jmacglashan I believe that Albin's `fallback_checkpoint_path` argument would allow you to do what you want.  PTAL.  I'm gonna mark closed for now but please reopen if this is still an issue!
