### ISSUE TITLE
What is the best way to write trajectories from multiple running actors into reverb ?

### ISSUE THREAD

**Issue by jrabary** [deepmind/reverb#19]
We're looking for an example of code on how to write full trajectories from multiples actors into reverb.
The setting is:
- N environments running in parallel (different process)
- variable episode length
- Use all trajectories once they are available
Our first idea is to create N different table for each running actors. But it is not clear how to retrieve all the 
trajectories from reverb and use them as a single dataset of trajectories.

**Comment by alaterre** [comment]
If you create one adder per actor, then I think reverb knows internally that the transitions come from different adders (and so trajectories) and manage that seamlessly. _To be verified/confirmed_

**Comment by acassirer** [comment]
Hey,

Sorry for the extremely late response on this issue!

The original response is indeed correct. As long as each actor uses their own writer then it is safe for them to all write to the same `Table` concurrently. When sampling the trajectories can be thought of the "atomic unit" so there is no need for the sampler to be aware of the number of actors on the other side of the system.
