### ISSUE TITLE
Error with reverb installation

### ISSUE THREAD

**Issue by samarjeet** [deepmind/reverb#2]
Thanks for making this project publicly available. I am checking it out. reverb installation is hitting the following error 

_ERROR: Could not find a version that satisfies the requirement dm-reverb-nightly==0.1.0.dev20200529; extra == "reverb" (from dm-acme[reverb]) (from versions: none)
ERROR: No matching distribution found for dm-reverb-nightly==0.1.0.dev20200529; extra == "reverb" (from dm-acme[reverb])_

**Comment by samarjeet** [comment]
It's python 3.8.2

**Comment by fastturtle** [comment]
The current dm-reverb-nightly release supports Python 3.6 and 3.7 (not 3.8). Can you try using one of those? We'll be including Python 3.8 support in our next dm-reverb-nightly release.

**Comment by fastturtle** [comment]
@samarjeet Reverb now supports Python 3.8, so it should work for you now. I'm closing this issue but please re-open if you continue to have issues.

**Comment by gaocegege** [comment]
I am using Python 3.8.6, facing the same issue here.

```
ERROR: Could not find a version that satisfies the requirement dm-reverb>=0.1.0; extra == "reverb" (from tf-agents[reverb]) (from versions: none)
ERROR: No matching distribution found for dm-reverb>=0.1.0; extra == "reverb" (from tf-agents[reverb])

**Comment by rish-16** [comment]
Hello there!

I'm facing similar installation issues on MacOS. Does Mac support `dm-reverb`? Any help would be great! 😃

**Comment by mwhoffman** [comment]
While reverb doesn't currently support macos, there is some movement in that direction that you can see here: https://github.com/deepmind/reverb/pull/24.

**Comment by windowshopr** [comment]
I'm having this same issue on Windows 10, Python 3.8. I just try to run the command `pip install --user dm-reverb` and get the errors:

```
ERROR: Could not find a version that satisfies the requirement dm-reverb (from versions: none)
ERROR: No matching distribution found for dm-reverb
```

Is it taken off of pypi or something?

**Comment by acassirer** [comment]
Hey @windowshopr, Reverb is Linux only and although there are some efforts in the Mac OS direction, Windows is very unlikely to ever be supported by the core team.

**Comment by Niloster** [comment]
Any updates on the MacOs version maybe?

**Comment by acassirer** [comment]
MacOs will never be supported by the core Reverb team I'm afraid.

**Comment by GuHuangAI** [comment]
@windowshopr Hi, I'm using Ubuntu22.04, python3.8.19, but still meet this issue. How to solve it?
