### ISSUE TITLE
The tutorial uses deprecated methods 

### ISSUE THREAD

**Issue by zhangxiaochuan** [deepmind/reverb#32]
Hi, I ran the [tutorial](https://github.com/deepmind/reverb/blob/master/examples/demo.ipynb) on both colab and the local machine, but it seems that some methods used in the tutorial are not supported in the current version of Reverb. Can you update the tutorial?

![image](https://user-images.githubusercontent.com/8330970/112266633-3e75b900-8caf-11eb-9364-68cb071814e1.png)

**Comment by MorganeAyle** [comment]
Hi, how did you solve this issue?

**Comment by zhangxiaochuan** [comment]
Actually, the tutorial is ahead of the release (v0.2.0). So, you can try the previous tutorials which match your reverb version: [v0.2.0 demo](https://github.com/deepmind/reverb/blob/3ac9ca2c162b3ec5c929ab6aa72558bfedb7447b/examples/demo.ipynb)

**Comment by zhangxiaochuan** [comment]
> Hi, how did you solve this issue?

Hi, @MorganeAyle. Actually, the tutorial is ahead of the release (v0.2.0). So, you can try the previous tutorials which match your reverb version: [v0.2.0 demo](https://github.com/deepmind/reverb/blob/3ac9ca2c162b3ec5c929ab6aa72558bfedb7447b/examples/demo.ipynb)

**Comment by MorganeAyle** [comment]
> > Hi, how did you solve this issue?
> 
> Hi, @MorganeAyle. Actually, the tutorial is ahead of the release (v0.2.0). So, you can try the previous tutorials which match your reverb version: [v0.2.0 demo](https://github.com/deepmind/reverb/blob/3ac9ca2c162b3ec5c929ab6aa72558bfedb7447b/examples/demo.ipynb)

Thank you!
