### ISSUE TITLE
Provide Windows binaries

### ISSUE THREAD

**Issue by cool-RR** [deepmind/reverb#33]
I use Windows. I wanted to use Acme to do RL research. Acme requires Reverb, and Reverb doesn't have Windows binaries for download. I don't know how to compile packages on my own. This means that now I can't use either Reverb or Acme.

**Comment by acassirer** [comment]
Hey,

I'm afraid that it is as you said. Reverb, and by extension Acme, is not available on Windows. We don't have any plans to support Windows at the moment and this is very unlikely to change in the future.
