### ISSUE TITLE
Acme's r2d2 fails due to reverb error 

### ISSUE THREAD

**Issue by apoorvabanubakode** [deepmind/reverb#34]
Hi, I am trying to run r2d2 agent from Acme, and it throws an error just after first episode is run: [reverb/cc/client.cc:159] Sampler and server are owned by the same process (21400) so Table priority_table is accessed directly without gRPC.
and the program is later killed.

Any idea why this is occurring and how can I get it to work?

Thanks!

**Comment by fastturtle** [comment]
Hi @apoorvabanubakode, the logging message you mention:

```
[reverb/cc/client.cc:159] Sampler and server are owned by the same process (21400) so Table priority_table is accessed directly without gRPC.
```

Is actually an [info message](https://github.com/deepmind/reverb/blob/2dadffec4629a972e649a8e0d4a4e057eb487e47/reverb/cc/client.cc#L162) to let users know that the table is being accessed without gRPC. If you can find the original error we may be able to help.

**Comment by ebrevdo** [comment]
Please provide the versions of TF, acme, and reverb you're using and a simple repro example.  Try to also provide a full paste of the error and the process dying.

Finally if you have time to do this yourself, run the subprocess that dies in gdb and when it dies, provide a stacktrace.  If you can't do that, the repro instructions may be sufficient for us to debug.
