### ISSUE TITLE
python3.9 support

### ISSUE THREAD

**Issue by sdumpling** [deepmind/reverb#36]
Installing reverb for python3.9 failed
ERROR: Could not find a version that satisfies the requirement dm-reverb>=0.2.0; extra == "reverb" (from tf-agents[reverb]) (from versions: none)
ERROR: No matching distribution found for dm-reverb>=0.2.0; extra == "reverb" (from tf-agents[reverb])

I also noticed that this package is marked for python3.{6,7,8} only. Is there any plan for supporting python3.9?

Thanks.

**Comment by fastturtle** [comment]
Hi @sdumpling we will eventually be adding python3.9 support but it is not a high priority for us. However if there are more requests for 3.9 support we can re-prioritize this.

**Comment by ebrevdo** [comment]
We are blocked on [TF supporting 3.9](https://github.com/tensorflow/tensorflow/issues/44485).  If they build for py3.9 in TF 2.5, we will be able to add appropriate tests.

**Comment by IanRDavies** [comment]
With today's [release](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0) of TF 2.5.0 there is TensorFlow support for Python 3.9. For the moment this seems to not be compatible with the stable release of `reverb`. (I have raised an issue about this #42)

**Comment by fastturtle** [comment]
The most recent Reverb release is compatible with TF 2.5.0 🎉

**Comment by tfboyd** [comment]
We do not have a 3.9 release yet.  I am looking at adding that build this week. Hopefully it is straight forward...although rarely is anything straight forward. Assigning this bug to me.

**Comment by tfboyd** [comment]
Quick update  @IanRDavies   Python 3.9 looks good. All test passed and the docker upgrade was super easy for once. I am making a couple small PRs/CLs. 99% chance I push the 3.9 build this week as 0.3.1 along with fresh 3.6 through 3.8.

**Comment by acassirer** [comment]
@IanRDavies Would you mind confirming that you are now able to use Reverb with Python 3.9?

**Comment by IanRDavies** [comment]
@acassirer I can confirm that reverb runs with Python 3.9. I haven't exhaustively tested all features but for all of my use cases it works!

**Comment by acassirer** [comment]
Awesome! Thanks @IanRDavies for verifying!
