### ISSUE TITLE
Sampling from multiple tables

### ISSUE THREAD

**Issue by MorganeAyle** [deepmind/reverb#37]
Hello, 
I want to create a buffer consisting of multiple queues, where each queue contains an ordered stream of observations. To construct a batch, I want to sample one observation from each queue and batch them (i.e. the batch size is the same as the number of queues). My idea is to create as many tables as queues needed, sample a batch size of 1 separately from each and then concatenate the result to get the desired batch. Is there a more efficient way of achieving this behavior?

**Comment by acassirer** [comment]
Hey,

If you need the different datasources to be kept separate then your approach will work. I'd suggest you look into [tf.Dataset.zip](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#zip) for merging the streams though.
