### ISSUE TITLE
"ImportError ... undefined symbol" in the demo.

### ISSUE THREAD

**Issue by uduse** [deepmind/reverb#44]
![image](https://user-images.githubusercontent.com/4717005/119420623-2aa00080-bcba-11eb-8df3-446100273dac.png)

[The notebook in the README.md]( https://github.com/deepmind/reverb/blob/master/examples/demo.ipynb) doesn't work. What I'm missing here? 🤔

**Comment by ebrevdo** [comment]
You need to install compatible versions of tensorflow and reverb.  For example if you're installing dm-reverb-nightly, you should also be installing tf-nightly.  If you're installing the latest stable version of reverb, I believe you want to use the appropriate major+minor version of tf.

What version of TF and reverb are you using?

**Comment by uduse** [comment]
Hi @ebrevdo , I merely ran the first two cells of the provided notebook and expected it to work. I managed to install the right versions by changing the command. See #45 for the updated version.

**Comment by acassirer** [comment]
#45 has now been merged so I'll go ahead and close down this issue. Thanks again @uduse for reporting and fixing the issue!
