### ISSUE TITLE
Table.queue() rate limiter not working

### ISSUE THREAD

**Issue by fedetask** [deepmind/reverb#48]
In the `reverb.rate_limiters.Queue()` docstring it's written 

> NOTE: Do not use this RateLimiter directly. Use Table.queue instead.

However, if I try to instantiate the following
```python
    server = reverb.Server(tables=[
        reverb.Table(
            name='my_table',
            sampler=reverb.selectors.Fifo(),
            remover=reverb.selectors.Fifo(),
            max_size=100
            rate_limiter=reverb.Table.queue('my_queue', 100)),
    ],
        port=8000
    )
```

The following is thrown

>   File "/home/fedetask/Desktop/python-venv/lib/python3.6/site-packages/reverb/server.py", line 160, in __init__
>   rate_limiter=rate_limiter.internal_limiter,
>   AttributeError: 'Table' object has no attribute 'internal_limiter'

**Comment by acassirer** [comment]
Hey,

Sorry for the confusion. The way you would use `reverb.Table.queue` is as follows:

```python
server = reverb.Server(
    tables=[Table.queue('my_queue', 100)],
    port=8000) 
```

It may help to take a look at the [example colab](https://github.com/deepmind/reverb/blob/master/examples/demo.ipynb) which has many examples like this one.
