### ISSUE TITLE
Why does ReplaySample returns a flat list instead of nested structure?

### ISSUE THREAD

**Issue by thisiscam** [deepmind/reverb#54]
Hi,

I was wondering if there's any particular reason why https://github.com/deepmind/reverb/blob/master/reverb/replay_sample.py#L53 returns a flat list for the python client?

**Comment by acassirer** [comment]
Hey,

That comment has grown a bit misleading with age. It used to be that the data was always flat but now the data **may be** structured. If the structure is available to the sampler (either by providing it explicitly or from the `Table` signature).

I'll update this docstring right away! Thanks for highlighting this!

**Comment by thisiscam** [comment]
Could you confirm when this behavior changed? Currently I'm using the stable release v0.3.1 on PyPI and it seems to be returning the flat list.
For what is worth, I did specified the Table signature when I setup the server.

**Comment by thisiscam** [comment]
mentioning @acassirer in case GitHub doesn't send notifications for a closed issue. Thanks!

**Comment by acassirer** [comment]
I don't recommend that the `client.sample` method is used for anything but debugging so it hasn't received much love. That being said, support for signatures in this method was added two weeks ago in [this change](https://github.com/deepmind/reverb/commit/a96e7ac7d5c918998fa2bc4ce65c38c6e1e5d400#diff-18e8674da950bde686bc1437e2d9b0d96c65cf43b28d391b03ccd709ccebdbd1) and is not present in any stable releases. It also is deactivated by default.

This will be available in the next stable release but that won't happen until tensorflow releases the next version. It is very easy to implement this yourself though by simply copying the behaviour introduced in that change.

**Comment by thisiscam** [comment]
Thanks for confirming!
