### ISSUE TITLE
Memory Leak caused during benchmarking reverb's performance?

### ISSUE THREAD

**Issue by bingykang** [deepmind/reverb#55]
Hi @ebrevdo,

I got some issues during benchmark the performance of reverb. The setting is as follows, 
- Setup one `Consumer` to sampling data from reverb, and multiple `Producer`s to generate data and add it to Reverb Server through the recommended `TrajectoryWriter`. 
- Each data element is a nested numpy array with `data_item = {'obs': np.array((84, 84, 4), dtype=np.uint8), 'reward': np.array((), dtype=np.int32)}`. Each data item contains 28236 Bytes or ~28Kb. 
- As adding more workers or `Producers`, it saturates at around 1.4Gb/s, as shown by the following figure. 

![image](https://user-images.githubusercontent.com/17242808/123590385-24eb8c80-d81d-11eb-856b-d0d907dd33d4.png)

My first question is that does the above performance look normal to you? 
The second one is when I run the program for a while, it crashes the machine. By checking the memory, we found that the memory usage grows very fast when there are 64 workers, which means there might be a memory leak? 

We also put the code below for your information. 

Commend to run it:
```
CUDA_VISIBLE_DEVICES='' python3 code_below.py --lp_launch_type=local_mp --num_workers 64
```
We are using a DGX-A100 machine to run the experiments, which has 256 cpu cores and 1024G memory. 

```python
"""Benchmarking reverb performance.  """
import itertools
import time

import numpy as np
import launchpad as lp
import reverb
import tensorflow as tf
import tree
from absl import app, flags

TEST_TABLE = 'queue'
FLAGS = flags.FLAGS
flags.DEFINE_integer('seq_length', 20, 'length of a trajectory')
flags.DEFINE_integer('batch_size', 64, 'the batch size to sample trajs')
flags.DEFINE_integer('num_workers', 64, 'number of producers')


class Spec:

  def __init__(self, shape, dtype):
    self.shape = shape
    self.dtype = dtype


spec = {'obs': Spec((84, 84, 4), np.uint8), 'action': Spec((), np.int32)}


def get_queue_size(client: reverb.Client) -> int:
  table_info = client.server_info()[TEST_TABLE]
  return (table_info.rate_limiter_info.insert_stats.completed -
          table_info.rate_limiter_info.sample_stats.completed)


class Producer:
  """A producer generate fake data."""

  def __init__(self, client, seq_length=1):
    self._client = client
    self._seq_length = seq_length

  def run(self):
    writer = self._client.trajectory_writer(
        num_keep_alive_refs=self._seq_length,
        get_signature_timeout_ms=300_000,
    )

    def randint(x):
      return np.random.randint(255, size=x.shape, dtype=x.dtype)

    for cnt in itertools.count(1):
      data = tree.map_structure(randint, spec)
      writer.append(data)
      if cnt % self._seq_length == 0:
        traj = tree.map_structure(lambda x: x[-self._seq_length:],
                                  writer.history)
        writer.create_item(TEST_TABLE, priority=1, trajectory=traj)


class Consumer:
  """A consumer to read data from the reverb server."""

  def __init__(self, client, seq_length, batch_size=1) -> None:
    self._client = client
    self._seq_length = seq_length
    self._batch_size = batch_size

  def _make_dataset(self):

    def _inner_make_dataset(unused_idx):
      ds = reverb.TrajectoryDataset.from_table_signature(
          server_address=self._client.server_address,
          table=TEST_TABLE,
          max_in_flight_samples_per_worker=100,
      )
      return ds

    num_parallel_calls = 16
    ds = tf.data.Dataset.range(num_parallel_calls)
    ds = ds.interleave(
        map_func=_inner_make_dataset,
        cycle_length=num_parallel_calls,
        num_parallel_calls=num_parallel_calls,
        deterministic=False,
    )

    ds = ds.batch(self._batch_size)
    ds.prefetch(-1)
    ds = iter(ds)

    return ds

  def run(self):
    ds = self._make_dataset()

    log_interval = 20
    step_size = self._batch_size * self._seq_length * 4

    t0 = time.time()
    for i in itertools.count(1):
      next(ds)
      if i % log_interval == 0:
        fps = int(i * step_size / (time.time() - t0))
        print('| FPS: {}, QSize: {}'.format(fps, get_queue_size(self._client)))


def main(_):

  seqlen, bs = FLAGS.seq_length, FLAGS.batch_size
  sig = tree.map_structure(
      lambda x: tf.TensorSpec(shape=(seqlen,) + x.shape, dtype=x.dtype),
      spec,
  )

  def make_queue():
    return [reverb.Table.queue(name=TEST_TABLE, max_size=10000, signature=sig)]

  program = lp.Program('BenchRerverb')

  with program.group('reverb'):
    client = program.add_node(lp.ReverbNode(make_queue))

  with program.group('Consumer'):
    program.add_node(
        lp.CourierNode(
            Consumer, client=client, seq_length=seqlen, batch_size=bs))

  with program.group('Producer'):
    for _ in range(FLAGS.num_workers):
      program.add_node(
          lp.CourierNode(Producer, client=client, seq_length=seqlen))

  lp.launch(program)


if __name__ == '__main__':
  app.run(main)
```

**Comment by acassirer** [comment]
Hey @bingykang,

I'm not @ebrevdo but I'll chip in anyway if you don't mind.

There is one thing that stands out to me as a potential source of the memory growth in the example you shared and that is that there isn't anything blocking on the producer side. This is likely to result in the local buffer of the `TrajectoryWriter` growing indefineteley until the system eventually OOM.

Lines to focus on are the following:

```python
for cnt in itertools.count(1):
  data = tree.map_structure(randint, spec)
  writer.append(data)
  if cnt % self._seq_length == 0:
    traj = tree.map_structure(lambda x: x[-self._seq_length:], writer.history)
    writer.create_item(TEST_TABLE, priority=1, trajectory=traj)
```

Neither `append` nor `create_item` block due to the state of the queue. What you need is a `flush` call after the `create_item` call. This will ensure that the program will block until the writer has received the confirmation that the item has been successfully inserted into the queue.

It is not obvious that the performance drop you see over time is due to this problem but it doesn't seem unlikely that memory allocation becomes slower due to less free memory being available. Maybe try adding the `flush`-call and rerun the benchmarks to verify that the memory (and hopefully speed) becomes stable?

_Sidenote: You would probably be able to achieve higher throughput by setting `block_until_num_items` to a value larger than 0. Check out the [documentation](https://github.com/deepmind/reverb/blob/master/reverb/trajectory_writer.py#L358) for details._

**Comment by bingykang** [comment]
Hi @acassirer,

Thank you so much for the quick reply!

The memory leak can be solved by adding `writer.flush(self._seq_length)` after `writer.create_item(TEST_TABLE, priority=1, trajectory=traj)`. 

A minor question is, it seems that adding `writer.flush` can not contribute to higher throughput. Could please make a guess on this? FYI, currently, the reverb queue is full and the sampler client (reading data from the server) saturates at 1.4Gb/s.

**Comment by acassirer** [comment]
Hey,

I'm not sure what the default behaviour of launchpad is here but if it launches the workers in a multithreaded context (i.e. from the same Python process) then the python GIL is probably getting in your way of reaching higher numbers.

Another guess is simply that 200k QPS is the limiting factor rather than the amount of data flying around. For the most part Reverb is quite agnostic to the size of the data and the limitations are more likely the mutex contention generated by the high QPS. 200k QPS is about the limit I'd expect to see from a queue setup.

One thing you could try to increase the performance is to use more than one queue while still using just one server. I experimented briefly with that when writing [the paper](https://arxiv.org/abs/2102.04736) and you can find some details in the appendix.

**Comment by fastturtle** [comment]
> I'm not sure what the default behaviour of launchpad is here but if it launches the workers in a multithreaded context (i.e. from the same Python process) then the python GIL is probably getting in your way of reaching higher numbers.

This is also my first thought. If this is the case @bingykang can you try launching with multi-processing instead?

**Comment by bingykang** [comment]
Hi @acassirer and @fastturtle, 

Actually, I am launching with local multiprocessing with 
```
CUDA_VISIBLE_DEVICES='' python3 code_below.py --lp_launch_type=local_mp --num_workers 64
```

BTW, The FPS in my case is 200K/s, it corresponds to a QPS of 50K/s, which aligns perfectly with Figure 7 in the paper with only one Table in the server. 

Another quick question, using multiple tables/queues to form one sampling dataset is not very straightforward to me, could you please elaborate more on this?

**Comment by sabelaraga** [comment]
About using multiple tables and sampling, you could build a dataset that interleaves single datasets, each of them sampling from a different table. For example, in ACME, it could be done by passing a table argument to _make_dataset https://github.com/deepmind/acme/blob/master/acme/datasets/reverb.py#L66

**Comment by bingykang** [comment]
Hi @sabelaraga,

Thank you for your reply, there is still a question about how to access the elements of a python list within an interleaved `map_fn`. I copy-paste acme's code over here,

```python
tables = ['name1', 'name2', 'name3']

def _make_dataset(unused_idx: tf.Tensor) -> tf.data.Dataset:
  dataset = reverb.TrajectoryDataset.from_table_signature(
      server_address=server_address,
      table=tables[unused_idx],
      max_in_flight_samples_per_worker=max_in_flight_samples_per_worker)

  # Finish the pipeline: batch and prefetch.
  if batch_size:
    dataset = dataset.batch(batch_size, drop_remainder=True)

  return dataset

# Create the dataset.
dataset = tf.data.Dataset.range(num_parallel_calls)
dataset = dataset.interleave(
    map_func=_make_dataset,
    cycle_length=num_parallel_calls,
    num_parallel_calls=num_parallel_calls,
    deterministic=False)
```

Suppose we have a list of table names `tables = ['name1', 'name2', 'name3']`, within `_make_dataset`, one should access the corresponding table name using `unused_idx`, which is actually a tf tensor, can not be used to index a python list. May I ask do you have any idea about this question?

**Comment by sabelaraga** [comment]
Hey @bingykang,

You may need to get the signature from the server using the `ServerInfo` call, and modify the `_make_dataset` function to use the `TrajectoryDataset` constructor with the shapes/dtypes fetched from the server:

```
def _make_dataset(table: tf.Tensor) -> tf.data.Dataset:
  return reverb.TrajectoryDataset(
      server_address=server_address,
      table=table,
      max_in_flight_samples_per_worker=max_in_flight_samples_per_worker,
      shapes=....,  # From the signature we fetched before.
      dtypes=....,  # From the signature we fetched before.
      ....)
```

You can also use a dataset of table names (instead of the range) as a base for interleaving:
```
tables_ds = tf.data.Dataset.from_generator(
    lambda: iter(["a", "b", "c"]), 
    output_signature=tf.TensorSpec([], tf.string))
```
Hope it helps!

**Comment by bingykang** [comment]
Thank you! It works well!

Unfortunately, I got another issue. By adding more reverb servers in this way, the FPS increases only a little bit (e.g., from 130K FPS with one server to 180K FPS with two servers, and to 200K FPS with 8 servers).

Does it look normal to you?

**Comment by bingykang** [comment]
FYI, I put the code here 
```python
self._cps = cps = 16  # number of parallel calls per server
self._addresses = [
    clients[i // cps].server_address for i in range(cps * len(clients))
]
# Get signature info
info = self._clients[0].server_info()
shapes = tree.map_structure(lambda x: x.shape, info[TEST_TABLE].signature)
dtypes = tree.map_structure(lambda x: x.dtype, info[TEST_TABLE].signature)

def _inner_make_dataset(server_address):
  ds = reverb.TrajectoryDataset(
      server_address=server_address,
      table=TEST_TABLE,
      max_in_flight_samples_per_worker=100,
      shapes=shapes,
      dtypes=dtypes,
  )
  return ds

num_parallel_calls = len(self._addresses)
ds = tf.data.Dataset.from_tensor_slices(self._addresses)
ds = ds.interleave(
    map_func=_inner_make_dataset,
    cycle_length=num_parallel_calls,
    num_parallel_calls=num_parallel_calls,
    deterministic=False,
)

ds = ds.batch(self._batch_size)
ds.prefetch(-1)
ds = iter(ds)
```

**Comment by sabelaraga** [comment]
The FPS sounds reasonable. In this case you're using multiple servers instead of multiple tables inside the same server, right?

**Comment by bingykang** [comment]
Yes

**Comment by acassirer** [comment]
Just a final note that you might as well just use a single server with multiple tables rather than multiple servers since they are all running on the same machine.

Closing this down now since the memory issue was resolved.
