### ISSUE TITLE
Storing tables on disk (vs. in-memory)

### ISSUE THREAD

**Issue by dtransposed** [deepmind/reverb#6]
In the current implementation, I understand that all the tables are stored in the memory, which can be possibly problematic for low-memory machines / substantial amount of experience. Is there possibly some way to avoid keeping full experience buffer in the memory? I have hoped for .ckpt files to do that, but it seems that they don't solve my problem.

**Comment by fastturtle** [comment]
Hi @dtransposed this is something we've discussed, but it isn't on our current roadmap. For substantial amounts of experience we spin up reverb servers on multiple machines and loadbalance between them.

**Comment by ebrevdo** [comment]
For now I'll mark this as closed; other than checkpointing we do not currently have on our roadmap a way to spill to disk.
