### ISSUE TITLE
Use dataset with varying action lengths

### ISSUE THREAD

**Issue by fedetask** [deepmind/reverb#60]
I want to store n-step transitions `s_1, a_1, r_1, s_2, a_2, r_2,  ...  s_n, a_n` where `a_n` is the last action of the sequence. This might be a common requirement for n-step learning (e.g. n-step SARSA).

I am having trouble creating a table with a signature that allows me to sample using datasets. The reason is that when I specify the signature I need to state the first dimension (number of steps). But in this case, the dimension for the actions might be `n` if `s_n` is not terminal, and `n-1` if `s_n` is terminal.

Is there a way to still create a dataset and sample from such a setting?

My workaround would be to insert "dummy" actions to make the lengths always match those declared in the signature, but I don't like this so much because I also need to store additional data (action logprobs, etc) and it would not be so clean. Otherwise, I'd give up using datasets and I'd just use the `sample()` method.  

EDIT:
I just realized that the last option (not using datasets but only the `sample()` method) does also not work for me:
```python
import reverb

server = reverb.Server(
    tables=[
        reverb.Table.queue('on_policy', max_size=10)
    ],
    port=8000
)

client = reverb.client.Client('localhost:8000')

with client.trajectory_writer(num_keep_alive_refs=123) as writer:
    writer.append({'state': 1, 'action': 1})
    writer.append({'state': 2, 'action': 2})
    writer.append({'state': 3})  # State 3 is terminal, no action inserted
    writer.create_item('on_policy', priority=0.0,
                       trajectory={
                           'states': writer.history['state'][-3:],
                           'actions': writer.history['action'][-3:-1]
                       })

samples = client.sample('on_policy', num_samples=1)
for sample in samples:
    print(sample)
```

Raises the error:
```
Traceback (most recent call last):
  File "reverb_test.py", line 26, in <module>
    for sample in samples:
  File "/home/fedetask/Desktop/python-venv/lib/python3.6/site-packages/reverb/client.py", line 391, in sample
    step, last = sampler.GetNextTimestep()
ValueError: Sampled trajectory cannot be decomposed into timesteps.
```

Currently, I'm going for the dummy data option:
```python
with client.trajectory_writer(num_keep_alive_refs=123) as writer:
    writer.append({'state': 1, 'action': 1, 'discount': 0.99})
    writer.append({'state': 2, 'action': 2, 'discount': 0.99})
    writer.append({'state': 3, 'action': DUMMY_ACTION, 'discount': 0.})  #Discount 0 signals terminal state  
    writer.create_item('on_policy', priority=0.0,
                       trajectory={
                           'states': writer.history['state'][-3:],
                           'actions': writer.history['action'][-3:]
                       })
```

**Comment by fedetask** [comment]
I just realized that the last option (not using datasets but only the `sample()` method) does also not work for me:
```python
import reverb

server = reverb.Server(
    tables=[
        reverb.Table.queue('on_policy', max_size=10)
    ],
    port=8000
)

client = reverb.client.Client('localhost:8000')

with client.trajectory_writer(num_keep_alive_refs=123) as writer:
    writer.append({'state': 1, 'action': 1})
    writer.append({'state': 2, 'action': 2})
    writer.append({'state': 3})  # State 3 is terminal, no action inserted
    writer.create_item('on_policy', priority=0.0,
                       trajectory={
                           'states': writer.history['state'][-3:],
                           'actions': writer.history['action'][-3:-1]
                       })

samples = client.sample('on_policy', num_samples=1)
for sample in samples:
    print(sample)
```

Raises the error:
```
Traceback (most recent call last):
  File "reverb_test.py", line 26, in <module>
    for sample in samples:
  File "/home/fedetask/Desktop/python-venv/lib/python3.6/site-packages/reverb/client.py", line 391, in sample
    step, last = sampler.GetNextTimestep()
ValueError: Sampled trajectory cannot be decomposed into timesteps.
```

**Comment by fedetask** [comment]
Currently, I'm going for the dummy data option:
```python
with client.trajectory_writer(num_keep_alive_refs=123) as writer:
    writer.append({'state': 1, 'action': 1, 'discount': 0.99})
    writer.append({'state': 2, 'action': 2, 'discount': 0.99})
    writer.append({'state': 3, 'action': DUMMY_ACTION, 'discount': 0.})  #Discount 0 signals terminal state  
    writer.create_item('on_policy', priority=0.0,
                       trajectory={
                           'states': writer.history['state'][-3:],
                           'actions': writer.history['action'][-3:]
                       })
```

**Comment by acassirer** [comment]
Hey,

For trajectories where some, or all, of the columns have varying length you just set the leading dimension to `None` in the dataset (and/or Table) signature. So for your example the signature might look something like this:

```python

signature={
    'observations': tf.TensorSpec([N, 100, 100]),
    'actions': tf.TensorSpec([None, 10]),
}
```

It is worth noting that with the new `TrajectoryWriter` the signature represent the **entire trajectory** as opposed to the legacy setup were the signature represent a single step within a trajectory. 

As for the broken `client.sample`. If you take a look at the docstring of `client.sample` you'll find [`emit_timesteps`](https://github.com/deepmind/reverb/blob/ceeb490bc63dad7ab3d4dfe116398e514cd610bf/reverb/client.py#L347). This defaults to `True` for legacy reasons but if you set this to `False` then your example should work.

Unfortunately this feature was added since the last stable release and thus will only work when using `dm-reverb-nightly`.

**Comment by fedetask** [comment]
Thanks, this is what I needed!

**Comment by acassirer** [comment]
Great :)
