### ISSUE TITLE
See how many samples are in Reverb table

### ISSUE THREAD

**Issue by jcformanek** [deepmind/reverb#63]
I would like to know how many samples are in my Reverb table. Is there a way to check this? 

Thanks for your assistance.

**Comment by sabelaraga** [comment]
Hey Claude,

You can get the information about the table with the [server_info call](https://github.com/deepmind/reverb/blob/master/reverb/client.py#L479), which returns a [TableInfo](https://github.com/deepmind/reverb/blob/3a7687feabefb4a72a0d7b1d72b8e5345748dba9/reverb/reverb_types.py#L52) object. Note that this is a snapshot, so if you are inserting/sampling, it might not be exact. Besides, this is different from the number of times the client can sample (that also depends on what's the sample per insert ratio, for example).

**Comment by jcformanek** [comment]
Many thanks, that is exactly what I needed.
