### ISSUE TITLE
Dataset sample hanging after restoring reverb server from checkpoint

### ISSUE THREAD

**Issue by jcformanek** [deepmind/reverb#64]
Hi there, I am trying to restore a reverb checkpoint. It seems I have successfully restored the reverb server since `client.server_info()` says that `current_size=357546` i.e. not zero. However, when I then make a reverb dataset and try to sample from it, my process just hangs without any errors. Does anyone know what I am doing wrong? Below is a snippet of my code.

```
checkpoint_path = "/tmp/tmp8ii1f6vm/"

checkpointer = reverb.checkpointers.DefaultCheckpointer(path=checkpoint_path)

replay_table = reverb.Table(
            name=reverb_adders.DEFAULT_PRIORITY_TABLE,
            sampler=reverb.selectors.Uniform(),
            remover=reverb.selectors.Fifo(),
            max_size=1000000,
            rate_limiter=reverb.rate_limiters.MinSize(1000),
            signature=sig,
        )

server = reverb.Server(tables=[replay_table], checkpointer=checkpointer, port=8000)

client = reverb.Client('localhost:8000')

print(client.server_info())

dataset = datasets.make_reverb_dataset(
            table=reverb_adders.DEFAULT_PRIORITY_TABLE,
            server_address='localhost:8000',
            batch_size=256,
            prefetch_size=4,
            sequence_length=None,
        )

print(next(iter(dataset)))
```

Thanks in advance for your help.

**Comment by sabelaraga** [comment]
Hey Claude, can you post what gets printed from the `server_info`? The only thing I can think of is if it's getting blocked by the RateLimiter, but it should be restored from the checkpoint as well.

**Comment by jcformanek** [comment]
Hi there, thanks for your reply. Now that you mention that the RateLimiter is also restored from the checkpoint, I think I know what I did wrong. I used a `sample per insert` RateLimiter originally but after I restored the reverb checkpoint I used a `min size` RateLimiter. Let me try fixing that quickly and I will let you know if it works. Thanks

**Comment by jcformanek** [comment]
Okay, it is still not working on my side. Here is the output from `server_info()`. I have omitted the signature because this comment is too cluttered with it. 

```
{'priority_table': TableInfo(name='priority_table', sampler_options=uniform: true
, remover_options=fifo: true
is_deterministic: true
, max_size=1000000, max_times_sampled=0, rate_limiter_info=samples_per_insert: 1.0
min_diff: -1.7976931348623157e+308
max_diff: 1.7976931348623157e+308
min_size_to_sample: 10
insert_stats {
  completed_wait_time {
  }
  pending_wait_time {
  }
}
sample_stats {
  completed_wait_time {
  }
  pending_wait_time {
  }
}
, signature=Transition([...]), current_size=1815, num_episodes=6, num_deleted_episodes=0)}
```

I notice that `rate_limiter_info` has `samples_per_insert: 1.0` even after I made sure I created the table with a `min size` RateLimiter. 

In my current setup I am trying to keep training my model on the experience in the reverb dataset after restoring from checkpoint without adding more data to reverb, i.e. I have a learner but no actors that collect more experience. I am trying to do a kind of offline RL experiment. 

Is the reverb server hanging because I am not inserting data? Is there a way for me to get around this? 

Or maybe I should look for a different solution for my use case. In particular, I am trying to collect a dataset of experience with an online agent and then train an offline agent on the checkpointed reverb dataset.

Many thanks for your help.

**Comment by sabelaraga** [comment]
One option to debug would be to enable insertion and see if sampling restarts.

The rate limiter uses the number of inserts/samples to determine if it's possible to sample: https://github.com/deepmind/reverb/blob/master/reverb/cc/rate_limiter.cc#L150

So one option could be that the rate limiter is not restored correctly.

**Comment by jcformanek** [comment]
Thanks for your help. I think I am not restoring the RateLimiter correctly. Ill close this issue because it does seem to be a problem on my side. But I will keep investigating.
