### ISSUE TITLE
client can not access reverb server in docker environment

### ISSUE THREAD

**Issue by tbund** [deepmind/reverb#8]
When running reverb in a docker environment, reverb client does not seem to be able to connect to the reverb server:

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    client.server_info()
  File "/test/lib/python3.8/site-packages/reverb/client.py", line 410, in server_info
    info_proto_strings = self._client.ServerInfo(timeout or 0)
RuntimeError: Socket closed
```

**Comment by MikeJanks** [comment]
Im having a similar issue. I spawn a multiprocess process and it cannot connect to reverb using reverb.Client('0.0.0.0:8000') or reverb.Client('localhost:8000') how ever it can work when using Threads instead. I cant use threads for my case so i hope someone can help me figure this out.

**Comment by acassirer** [comment]
My guess here is that port 8000 opened from one docker container isn't necessarily mapped to port 8000 on the second. The fact that you see no issues when using threads supports this hypothesis (as both would be running under the same process and thus share container).

[This](https://stackoverflow.com/questions/19948149/can-i-run-multiple-programs-in-a-docker-container) seems like it might be relevant. The [network documentation for docker](https://docs.docker.com/network/) also seems like a good place to start.

**Comment by samarth-robo** [comment]
I am observing this issue when trying to run the reverb quick start example in SLURM. @tbund did you manage to fix it? Thanks.
