### ISSUE TITLE
Sampling terribly slow

### ISSUE THREAD

**Issue by mikygit** [deepmind/reverb#80]
Hello,
 I've been playing with reverb for a few days and I notoced that sampling is terribly slow as opposed to insertions.

Although the server_info tells me that I'm sampling at a rate or approximately 45k items per sec, on the client side, it's more close to 1 item per sec :-(

My client and server are running on 2 seperate machines at the moment but I also tried having both the client and the server on the same machine (and also in the same process) in vain.
It's still very slow.

Stored data are quadriplet of numpy arrays (obs, actions, ...)
The config of the server is the one found in the Readme, nothing fancy.
The client retrieves data per 256 num_samples. 64 times. I tried to sample everything in once with no effect.
I'm using client.sample(table_name, num_samples) to sample.
There are up to one million items in the table but it is slow even with 2000 items.
And I'm using pytorch.

I'm a bit disapointed ... Any idea, recommandations?

Thanx!

**Comment by qstanczyk** [comment]
Is the data being added to the table in the background? Could sampling be slow due to the setting of the rate limiter which could block sampling? What is the CPU usage of Reverb? If it is low, this is most likely the rate_limiter or networking throughput issue.
