### ISSUE TITLE
Pb using TrajectoryDataset

### ISSUE THREAD

**Issue by mikygit** [deepmind/reverb#83]
Hello,
 Is there a way to use a TrajectoryDataset without having to specify tables signatures? Or use some kinda 'Any' keyword?

Would be quiet usefull to use the replay buffer on different kind of gym environement for instance.

Thanx!

nb: using pytorch

**Comment by acassirer** [comment]
Hi,

I'm afraid that will not be possible since tf.data requires that the shapes and dtypes are known.
