### ISSUE TITLE
How to customize a selector

### ISSUE THREAD

**Issue by liyingathere** [deepmind/reverb#87]
If I want to customize the selector of reverb, what steps should I follow?
How to compile the reverb from source(for Linux)?
Is there any documentation for the above two questions?
Thank you.

**Comment by qstanczyk** [comment]
Please have a look at the documentation regarding [building from source](https://github.com/deepmind/reverb/blob/master/reverb/pip_package/README.md#how-to-develop-and-build-reverb-with-the-docker-containers).

For selectors - you can read about them in the [documentation as well](https://github.com/deepmind/reverb/tree/4bdbb9895632d793e0fbdc509c1bfb23f1096b9d#item-selection-strategies)
or please refer to the implementation for details [example](https://github.com/deepmind/reverb/blob/fdcdf7385b8ed63ac8cc418ebb187e8543bcf576/reverb/cc/selectors/fifo.h#L27).
