### ISSUE TITLE
Feature request: Make an Item reference sampled data in a second table

### ISSUE THREAD

**Issue by SRaent** [deepmind/reverb#93]
I have a quite specific usage case where i need to annotate data from a table which i just sampled. I need a second table which then contains the sampled data annotated with additional data. An obvious but inefficient solution is to store a copy of the sampled data in the  second table together with the annotation.
The reverb documentation clearly states, that an item can reference different chunks. Therefor i guess that this is technically possible and maybe i just don't know how to implement it.

Here is a code example of the inefficient implementation:
```
import tensorflow as tf
import reverb


rt = reverb.Table(
        't1',
        reverb.selectors.Uniform(), 
        reverb.selectors.Fifo(), 
        1000, 
        reverb.rate_limiters.MinSize(1),
        signature=tf.TensorSpec(1)
        )

rt2 = reverb.Table(
        't2',
        reverb.selectors.Uniform(), 
        reverb.selectors.Fifo(), 
        1000, 
        reverb.rate_limiters.MinSize(1),
        signature=tf.TensorSpec(2)
        )

server = reverb.Server(
        [rt,rt2]
        )

client = reverb.Client(f'localhost:{server.port}')

with client.trajectory_writer(1) as w:
    w.append(tf.random.uniform([1]))
    w.create_item('t1',1,w.history[0])


tds = reverb.TrajectoryDataset.from_table_signature(
        f'localhost:{server.port}',
        't1',
        10,
        )


for s in tds.take(1):
    #sample data
    print(s.data)
    with client.trajectory_writer(1) as w:
	#annotate sampled data and save the sampled data in a new
	#table together with the annotation
	#a copy of the sampled data is saved, making this inefficient
        w.append(tf.concat([s.data,tf.random.uniform([1])],0))
        w.create_item('t2',1,w.history[0])

```

**Comment by qstanczyk** [comment]
Item can reference other items in case for instance when items are N-step transitions. In such case, to avoid storing the same step N times, Reverb client tracks re-usage of the steps. In your case, however, when you sample an item and add it to the second table (with annotations) it is not possible (trivial to do). Hence 2x storage is the easiest/best way to go.
