### ISSUE TITLE
ImportError in conda environment

### ISSUE THREAD

**Issue by zhengmingli18** [deepmind/reverb#95]
Step to reproduce:

```python
conda create -n tf-agents python
conda activate tf-agents
pip install tf-agents[reverb]
python
>>>import reverb
```

The error I get is:

```shell 
File "xxx/anaconda3/envs/tf-agents/lib/python3.10/site-packages/reverb/pybind.py", line 4, in <module>
    from .libpybind import *
ImportError: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
```

But I can find the file ( `libpython3.10.so.1.0` ) in `···/anaconda3/envs/tf-agents/lib`.
<img width="1074" alt="WX20220410-223215@2x" src="https://user-images.githubusercontent.com/90447343/162624360-04a06d74-def3-418c-b119-1c29f259bdca.png">

I have tried many methods before, including：
- `sudo apt-get install libpython3.10`
    - but I get `Unable to locate package libpython3.10`
-  export LD_LIBRARY_PATH=xxx
- create a soft link between the file and /lib
- Various versions (Python, TensorFlow, TF-Agents, Reverb)

Could you please help me to solve this problem?

Thank you in advance

Can you help me solve this problem?

Thank you in advance.

**Comment by sabelaraga** [comment]
Hi, do you have Python 3.10 installed? (sudo apt install python3.10 should work).

**Comment by zhengmingli18** [comment]
> Hi, do you have Python 3.10 installed? (sudo apt install python3.10 should work).

Yep, My Python version is 3.10.4

**Comment by sabelaraga** [comment]
Thanks for checking (just ruling out the basic errors, I didn't realize `find libpython3.10.so.1.0` was successful on your setup).
What we install to compile reverb is:
* python3.10-dev
* python3.10-distutils
(afaik, distutils is for packaging, so it shouldn't be needed here).

More details in the dockerfile [here](https://github.com/deepmind/reverb/blob/master/docker/release.dockerfile).

**Comment by zhengmingli18** [comment]
Are you saying that reverb cannot be successfully installed through `pip install tf-agents[reverb]`?

**Comment by zhengmingli18** [comment]
I have solved this problem successfully.

If you can find `libpython3.10.so.1.0` in `/path-to-conda/envs/your-env-name/lib` and your IEDA is 'PyCharm', you can try the following methods：

1. select the file contained `import reverb`.
2. Run->Edit configurations.
3. add `LD_LIBRARY_PATH=/home/zmli/anaconda3/envs/tf-agents-nightly/lib` in environment variables.
4. run the file.

This is my own configuration problem.  
 I'm sorry for consuming @sabelaraga  ‘s time.
Thanks for you help and I close it.
