### ISSUE TITLE
Import error after installation

### ISSUE THREAD

**Issue by Mrinal18** [deepmind/reverb#96]
Hello,

I am trying to install reverb and i see this particular message when i try to import `reverb`

ImportError: cannot import name 'pybind' from partially initialized module 'reverb' (most likely due to a circular import) (/home/chip/Desktop/Utils/reverb/reverb/__init__.py)

Tensorflow version: 2.10.0-dev20220417
OS: CentOs
python version: 3.9.12

commands used to install :  (as per the documentation README) 

Kindly help on this,
Thanks

**Comment by acassirer** [comment]
Hi,

I'm afraid that I have no experience with CentOS so I can't really give you any advice on how to debug the issue. Maybe CentOS is not compatible with [pybind11](https://github.com/pybind/pybind11)?

I'd also recommend you to also try initializing an empty virtualenv and installing Reverb together with tensorflow. On a Debian system this worked without any issues:

```
$ mkdir test
$ cd test 
$ python3 -m venv venv
$ source ./venv/bin/activate
$ pip install "dm-reverb[tensorflow]"
```

**Comment by qstanczyk** [comment]
Please reopen if this is still an issue.
